### ISSUE TITLE
Choose a task management platform

### ISSUE THREAD

**Issue by yarons** [Maagan-Michael/invitease#17]
As suggested by @dangalg in #7 we should try and utilize a task management platform.

Since we don't really have agile development methodology I'm not sure it's super relevant but we have the following suggestions:
Taiga - Open source.
Trello - Free but commercial.
WeKan - Open source.
*GitHub Projects - Closed source, builtin.

We can also work with assigning Issues to ourselves.

**Comment by yarons** [comment]
@dangalg I've created an automated Kanban board here in GitHub, just click the Projects Tab and look for Invitease.

@inbarbarkai Do you think it's good enough for us?

Would you guys prefer something other than Kanban?

**Comment by yarons** [comment]
Any thoughts about this offering? Do you guys prefer something else?

**Comment by inbarbarkai** [comment]
I think the GitHub issues is good enough for now.
