### ISSUE TITLE
creation_timestamp & modify_timestamp missing from event_log

### ISSUE THREAD

**Issue by yarons** [Maagan-Michael/invitease#36]
@inbarbarkai I've noticed a small diff between your implementation and the wiki.

https://github.com/Maagan-Michael/invitease/blob/master/db_init/baseline.sql#L34

In the wiki we've documented it like this:

    * creation_timestamp - When was this entry created.
    * modify_timestamp - When was the last action performed on this entry.

Not sure if we need it, what do you think?

**Comment by inbarbarkai** [comment]
No need for those fields.
Logs aren't suppose to be changed.

**Comment by yarons** [comment]
True, removing these.

@KamiTzayig I'm documenting accordingly.
