### ISSUE TITLE
Split to components

### ISSUE THREAD

**Issue by yarons** [Maagan-Michael/invitease#7]
As proposed by both @YBB8201 and @dangalg we would like to split the project into components to avoid collisions and merge conflicts.

We should first decide what will the different components be and then split the work into subunits and tasks and start working on separate files and branches for each component.

**Comment by dangalg** [comment]
How do you suggest we do this? Trello?

**Comment by yarons** [comment]
Inbar already divided it.
There's the open source Taiga, I think we should try to leverage open source solutions just for the sake of continuity.
I'm also involved with WeKan, which is an open source Kanban task manager but I don't know if there's any free plan or free hosting for it.

Any other suggestions?

PS I've moved this discussion to #17, thanks.

**Comment by yarons** [comment]
Resolved by #11.
